# Chat domain — import from submodules directly:
#   from app.services.chat.handler import handle_natural_conversation, ICP_PRODUCT_NAMES, ...
#   from app.services.chat.quick_classifier import ClassificationResult, ProblemCategory, ...
